services:
  db:
    image: postgres:17.0
    restart: always
    env_file:
      - "db.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  app:
    build: .
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
    command: /app/app
