services:
  db:
    image: postgres:17.0
    restart: always
    env_file:
      - "db.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - "db_data:/var/lib/postgresql/data"
  app:
    build: .
    env_file:
      - ".env"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 3 && /app/app"
    restart: always
volumes:
  db_data: